### PR TITLE
Add Typescript definitions

### PR DESCRIPTION
**Pull request by pmwmedia**
I'm using Webpack with Typescript configuration files. These are my Typescript definitions for your plugin to make it ready for Typescript.

### CODE REVIEW

**Comment by zsimo** [comment]
thanks for the types definitions!

**Comment by pmwmedia** [comment]
@zsimo: Thank you for the fast merge and your awesome webpack plug-in! Finally I have found a great and easy way to reload all my Javascript bundles from my Jetty server.

**Comment by pmwmedia** [comment]
@zsimo I'm just updating to handmade-livereload-webpack-plugin 2.4.0. The `package.json` contains the `types` property, but `index.d.ts` itself is missing.

**Comment by zsimo** [comment]
@pmwmedia  fixed in 2.4.1

**Comment by pmwmedia** [comment]
Thank you! Works perfectly now :)

**Pull request merged**
